layout_spectrum: 0.2287933
typography_spectrum: 0.8847073
color:
  saturation: 0.7440145
  lightness: 0.1467787
  brandStrength: 1
  brandColors:
    - '#FFFFFF'
    - '#955A0E'
    - '#707070'
    - '#B28556'
    - '#CFB497'
  rhythmicContrast: 0.8015826
name: 'Angel Francisco Condom, PA'
