layout_spectrum: 0.4868578
color:
  saturation: 0.4749103
  lightness: 0.6338112
  brandStrength: 1
  brandColors:
    - '#FFFFFF'
    - '#955A0E'
    - '#707070'
    - '#B28556'
    - '#CFB497'
  rhythmicContrast: 1
typography_spectrum: 0.8847073
name: 'Angel Francisco Condom, PA'
